---

# https://www.gnome-look.org/p/1529571

- name: Copy the Theme files to /boot/grub/themes
  hosts: localhost
  tasks:
    - name: Create grub themes directory
      file:
        path: /boot/grub/themes/pushit
        state: directory
        owner: root
        group: root
        mode: 0755
        recurse: yes
    - name: copy the PUSH IT grub theme to remote
      ansible.builtin.copy:
        src: ./pushit/
        dest: /boot/grub/themes/pushit
        remote_src: no
        directory_mode: yes
    - name: modify grub settings in /etc/default/grub for timeout
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_TIMEOUT='
        line: GRUB_TIMEOUT=5
      register: grubupdate1

    - name: modify grub settings in /etc/default/grub for style menu
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        line: "GRUB_TIMEOUT_STYLE=menu"
        state: present
        backup: yes
      register: grubupdate2

    - name: modify grub settings in /etc/default/grub for theme
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        line: "GRUB_THEME=\"/boot/grub/themes/pushit/theme.txt\""
        state: present
        backup: yes
      register: grubupdate3

    - name: update-grub
      shell: update-grub2
      when: (grubupdate1 is changed or grubupdate2 is changed or grubupdate3 is changed) 

