---

- name: some tunings on x server
  hosts: localhost
  tasks:
    - name: get user with id 1000 (primary user for debian)
      shell: >
        getent passwd 1000 | 
        awk -F: '{ print $1 }'
      changed_when: false
      register: username   
    - name: Set the scaling options for 4k displays
      template:
        src: ./configs/.Xresources
        dest: /home/{{ username.stdout }}/.Xresources
        owner: '{{ username.stdout }}'
        group: '{{ username.stdout }}'
        remote_src: no