---

# install the desktop environemnt with XORG, Windowmanager, Polybar etc

- name: Check if dedicated NVIDIA graficcard is built in and install drivers
  hosts: localhost
  tasks:
    - name: Install xorg and other tools
      apt:
        pkg: 
          - xorg
          - bspwm
          - polybar
          - dmenu
        state: latest
        update_cache: yes
    - name: Autoremove lemonbar
      apt:
        pkg:
          - lemonbar
        autoremove: yes
        purge: yes
    - name: get user with id 1000 (primary user for debian)
      shell: >
        getent passwd 1000 | 
        awk -F: '{ print $1 }'
      changed_when: false
      register: username 

    - name: Creating .xinitrc
      copy:
        dest: "/home/{{ username.stdout }}/.xinitrc"
        content: |
          xrdb -merge ~/.Xresources
          exec bspwm
        owner: '{{ username.stdout }}'
        group: '{{ username.stdout }}'  
        
    - name: Changing perm of .xinitrc, adding "+x"
      file: dest="/home/{{ username.stdout }}/.xinitrc" mode=a+x

    - name: Create config dirs for bspwm
      file:
        path: /home/{{ username.stdout }}/.config/bspwm
        state: directory
        owner: '{{ username.stdout }}'
        group: '{{ username.stdout }}'
        mode: 0755
        recurse: yes

    - name: Create config dirs for sxhkd
      file:
        path: /home/{{ username.stdout }}/.config/sxhkd
        state: directory
        owner: '{{ username.stdout }}'
        group: '{{ username.stdout }}'
        mode: 0755
        recurse: yes

    - name: Create config dirs for polydar
      file:
        path: /home/{{ username.stdout }}/.config/polybar
        state: directory
        owner: '{{ username.stdout }}'
        group: '{{ username.stdout }}'
        mode: 0755
        recurse: yes




    - name: Copy config bspwmrc
      ansible.builtin.copy:
        src: ./configs/bspwmrc
        dest: /home/{{ username.stdout }}/.config/bspwm/bspwmrc
        owner: '{{ username.stdout }}'
        group: '{{ username.stdout }}'
        mode: 'a+x'
        remote_src: no

    - name: Copy config sxhkd
      ansible.builtin.copy:
        src: ./configs/sxhkdrc
        dest: /home/{{ username.stdout }}/.config/sxhkd/sxhkdrc
        owner: '{{ username.stdout }}'
        group: '{{ username.stdout }}'
        mode: 'a+x'
        remote_src: no

    - name: Copy config polybar
      ansible.builtin.copy:
        src: ./configs/polybar
        dest: /home/{{ username.stdout }}/.config/polybar/config
        owner: '{{ username.stdout }}'
        group: '{{ username.stdout }}'
        mode: 'a+x'
        remote_src: no

    - name: Copy polybar launcher
      ansible.builtin.copy:
        src: ./scripts/polybar_launcher.sh
        dest: /home/{{ username.stdout }}/.config/polybar/launch.sh
        owner: '{{ username.stdout }}'
        group: '{{ username.stdout }}'
        mode: 'a+x'
        remote_src: no
