---
- name: Check if dedicated NVIDIA graficcard is built in and install drivers
  hosts: localhost
  tasks:
    - name: check lspci for NVIDIA VGA
      shell: lspci | grep VGA | grep NVIDIA
      register: checknvidia
      failed_when: checknvidia.rc > 1
    - name: print debug message if NVIDIA is found
      ansible.builtin.debug:
        msg:
          - "NVIDIA Grafic Card found."
      when: checknvidia.rc == 0
    - name: print debug message if NVIDIA is not found
      ansible.builtin.debug:
        msg:
          - "NVIDIA Grafic Card NOT found."
      when: checknvidia.rc == 1
    - name: Add bullseye-backports repository into sources list
      ansible.builtin.apt_repository:
        repo: deb http://deb.debian.org/debian bullseye-backports main contrib non-free
        state: present
      when: (checknvidia.rc == 0 and ansible_facts['distribution'] == "Debian" and ansible_facts['lsb']['major_release'] == "11")
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install NVIDIA driver
      apt:
        pkg: 
          - bullseye-backports
          - nvidia-driver 
          - firmware-misc-nonfree
        state: present
        update_cache: yes
      when: checknvidia.rc == 0
