---
- name: Installing common used tools
  hosts: localhost
  tasks:
    - name: Install common used tools
      apt:
        pkg: 
          - nvtop
          - psmisc
          - htop
          - vim
          - curl
          - wget
        state: latest
        update_cache: yes
